name: 'bundler-audit with reviewdog'
description: 'Run bundler-audit with reviewdog on pull requests to improve security review experience.'
author: 'buck-ai'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.GITHUB_TOKEN }}'
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-check,github-pr-review,github-pr-annotations].'
    default: 'github-pr-review'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
runs:
  using: "composite"
  steps:
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: v0.17.1
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
branding:
  icon: activity
  color: red